apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-bpm-demo

resources:
  -
imagecamunda/camunda-bpm-platform:7.11.0

configMapGenerator:
- name: camunda-bpm-config
  files:
  - prometheus-jmx-config.yaml

# patchesStrategicMerge:
# - service_port_8888.yaml
