apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-bpm-demo

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/env: demo
  app.kubernetes.io/app: camunda-bpm

bases:
  - ./engine

resources:
  - namespace.yaml

images:
  # - name: postgres
    # newName: my-registry/my-postgres
    # newTag: v1
  - name: camunda-bpm
    newName: camunda/camunda-bpm-platform
    newTag: tomcat-7.11.0

vars:
  - name: HOSTNAME
    fieldref:
      fieldPath: data.hostname
  - name: CERTISSUER
    fieldref:
      fieldPath: data.certIssuer
  - name: TLSACME
    fieldref:
      fieldPath: data.tlsAcme
  - name: INGRESSCLASS
    fieldref:
      fieldPath: data.ingressClass
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: site-config
