apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/component: engine
resources:
  - deployment.yaml

configMapGenerator:
- name: camunda-bpm-config
  files:
  - engine/prometheus-jmx-config.yaml
