apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-bpm-demo

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/env: demo
  app.kubernetes.io/app: camunda-bpm

bases:
  - ./platform

resources:
  - namespace.yaml
  - site-data.yaml

# prometheus jmx container adds the jar
images:
  - name: prometheus-jmx-exporter
  - newName: gcr.io/camunda-cloud-240911/prometheus-jmx-exporter

# set url specific data and configure tls
patchesStrategicMerge:
  - ingress-patch.yaml

vars:
  - name: HOSTNAME
    fieldref:
      fieldPath: data.hostname
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: site-data
