apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/camunda-cloud-240911/prometheus-jmx-exporter
    context: ./images/prometheus-jmx-exporter
  googleCloudBuild: {}
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    path: .
