apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: gcr.io/camunda-cloud-240911/camunda-bpm
    context: ./images/camunda-bpm
  googleCloudBuild: {}
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    path: .
