apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: camunda-bpm-demo

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: camunda-bpm-demo

resources:
  - ./engine
  - namespace.yaml

images:
  # - name: postgres
    # newName: my-registry/my-postgres
    # newTag: v1
  - name: camunda-bpm
    newName: camunda/camunda-bpm-platform
    newTag: tomcat-7.11.0
